# Generated by Django 5.1 on 2024-11-08 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_calendarioitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='skills',
        ),
        migrations.AddField(
            model_name='skill',
            name='nivel',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('skills', models.ManyToManyField(blank=True, to='app.skill')),
            ],
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='cargo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.cargo'),
        ),
    ]
